# frozen_string_literal: true

source 'https://rubygems.org'

gem 'activerecord'
gem 'activesupport'
gem 'boxcars'
gem 'charty'
gem 'cosine-similarity'
gem 'daru'
gem 'daru-view', github: 'SciRuby/daru-view'
gem 'eqn', '~> 1.6.5'
gem 'eth', github: 'q9f/eth.rb'
gem 'google_search_results'
gem 'gruff'
# gem 'iruby'
# gem 'langchainrb'
gem 'langchainrb', github: 'geeknees/langchainrb', branch: 'eth'
gem 'matrix'
gem 'numo-narray'
gem 'nyaplot', github: 'SciRuby/nyaplot'
gem 'open-weather-ruby-client', '~> 0.3.0'
gem 'pg'
gem 'rb_prob', github: 'geeknees/rb_prob'
gem 'red-datasets'
gem 'rubocop'
gem 'ruby-openai'
gem 'safe_ruby', '~> 1.0.4'
gem 'sequel', '~> 5.68.0'
gem 'wikipedia-client', '~> 1.17.0'
